using System.Text;
using ProceduralMapGenerator.Core.Models;

namespace ProceduralMapGenerator.Core.Export.Unity;

public static class UnityReadmeGenerator
{
    public static string GenerateReadme(Map map, int seed, string generatorType)
    {
        var sb = new StringBuilder();

        Title(sb);
        ImportGuide(sb);
        Structs(sb);
        ExampleMonoBehaviour(sb);
        TilemapTip(sb, generatorType);
        Stats(sb, map, seed, generatorType);

        return sb.ToString();
    }

    // ── Sections ──────────────────────────────────────────────────────────────

    private static void Title(StringBuilder sb)
    {
        sb.AppendLine("# ProceduralMapGenerator — Unity Integration Guide");
        sb.AppendLine();
        sb.AppendLine("> Auto-generated by ProceduralMapGenerator.  ");
        sb.AppendLine("> Import the companion `.json` file into your Unity project using the steps below.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void ImportGuide(StringBuilder sb)
    {
        sb.AppendLine("## How to Import This JSON");
        sb.AppendLine();
        sb.AppendLine("### Option A — JsonUtility (built-in, zero extra packages)");
        sb.AppendLine();
        sb.AppendLine("> ⚠️ `JsonUtility` does not support `null` object references.");
        sb.AppendLine("> If `lastPath` is absent from the JSON, leave this field out of the struct");
        sb.AppendLine("> or use Option B instead.");
        sb.AppendLine();
        sb.AppendLine("1. Copy the `.json` file into `Assets/Resources/` (no extension in the load call).");
        sb.AppendLine("2. Load and deserialize:");
        sb.AppendLine();
        sb.AppendLine("```csharp");
        sb.AppendLine("TextAsset jsonAsset = Resources.Load<TextAsset>(\"dungeon_seed_42\");");
        sb.AppendLine("UnityMapData data   = JsonUtility.FromJson<UnityMapData>(jsonAsset.text);");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("### Option B — Newtonsoft.Json (recommended)");
        sb.AppendLine();
        sb.AppendLine("Install via **Window → Package Manager → Add by name**: `com.unity.nuget.newtonsoft-json`");
        sb.AppendLine();
        sb.AppendLine("```csharp");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine();
        sb.AppendLine("TextAsset jsonAsset = Resources.Load<TextAsset>(\"dungeon_seed_42\");");
        sb.AppendLine("UnityMapData data   = JsonConvert.DeserializeObject<UnityMapData>(jsonAsset.text);");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("### Option C — StreamingAssets (runtime file access)");
        sb.AppendLine();
        sb.AppendLine("```csharp");
        sb.AppendLine("string filePath = Path.Combine(Application.streamingAssetsPath, \"dungeon_seed_42.json\");");
        sb.AppendLine("string json     = File.ReadAllText(filePath);");
        sb.AppendLine("UnityMapData data = JsonConvert.DeserializeObject<UnityMapData>(json);");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void Structs(StringBuilder sb)
    {
        sb.AppendLine("## C# Unity Structs");
        sb.AppendLine();
        sb.AppendLine("Copy the following into any `.cs` file in your Unity project.");
        sb.AppendLine("Field names match the camelCase JSON keys exactly.");
        sb.AppendLine();
        sb.AppendLine("```csharp");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine("public class UnityMapData");
        sb.AppendLine("{");
        sb.AppendLine("    public string         generatorType;  // \"BSP\" or \"Terrain\"");
        sb.AppendLine("    public int            width;");
        sb.AppendLine("    public int            height;");
        sb.AppendLine("    public int            seed;");
        sb.AppendLine("    public string         generatedAt;    // ISO 8601");
        sb.AppendLine("    public UnityRoomData[] rooms;");
        sb.AppendLine("    public UnityTileData[] tiles;         // flat row-major: index = y * width + x");
        sb.AppendLine("    public UnityPathData   lastPath;      // null when no path was generated");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine("public class UnityRoomData");
        sb.AppendLine("{");
        sb.AppendLine("    public string id;          // \"room_0\", \"room_1\", …");
        sb.AppendLine("    public int    x, y;");
        sb.AppendLine("    public int    width, height;");
        sb.AppendLine("    public int    centerX, centerY;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine("public class UnityTileData");
        sb.AppendLine("{");
        sb.AppendLine("    public int    x, y;");
        sb.AppendLine("    public string tileType;    // \"Floor\", \"Wall\", \"Door\", \"Corridor\", \"Empty\"");
        sb.AppendLine("    public bool   isWalkable;");
        sb.AppendLine("    public string biomeType;   // null for BSP; \"Forest\", \"Grassland\" … for Terrain");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine("public class UnityPathData");
        sb.AppendLine("{");
        sb.AppendLine("    public UnityVector2Int[] waypoints;");
        sb.AppendLine("    public int               length;");
        sb.AppendLine("    public int               nodesExplored;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("[Serializable]");
        sb.AppendLine("public struct UnityVector2Int");
        sb.AppendLine("{");
        sb.AppendLine("    public int x, y;");
        sb.AppendLine("}");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void ExampleMonoBehaviour(StringBuilder sb)
    {
        sb.AppendLine("## Example MonoBehaviour");
        sb.AppendLine();
        sb.AppendLine("Save as `LoadMap.cs` anywhere inside `Assets/`:");
        sb.AppendLine();
        sb.AppendLine("```csharp");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.Tilemaps;");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine();
        sb.AppendLine("public class LoadMap : MonoBehaviour");
        sb.AppendLine("{");
        sb.AppendLine("    [Header(\"Data\")]");
        sb.AppendLine("    [SerializeField] private TextAsset mapJson;");
        sb.AppendLine();
        sb.AppendLine("    [Header(\"Tilemap\")]");
        sb.AppendLine("    [SerializeField] private Tilemap tilemap;");
        sb.AppendLine();
        sb.AppendLine("    [Header(\"Tile Assets\")]");
        sb.AppendLine("    [SerializeField] private TileBase floorTile;");
        sb.AppendLine("    [SerializeField] private TileBase wallTile;");
        sb.AppendLine("    [SerializeField] private TileBase doorTile;");
        sb.AppendLine("    [SerializeField] private TileBase corridorTile;");
        sb.AppendLine();
        sb.AppendLine("    private UnityMapData    _data;");
        sb.AppendLine("    private UnityTileData[,] _grid;  // [x, y] for O(1) lookup");
        sb.AppendLine();
        sb.AppendLine("    void Start()");
        sb.AppendLine("    {");
        sb.AppendLine("        // 1. Deserialise JSON");
        sb.AppendLine("        _data = JsonConvert.DeserializeObject<UnityMapData>(mapJson.text);");
        sb.AppendLine();
        sb.AppendLine("        // 2. Build random-access 2D grid from flat array");
        sb.AppendLine("        //    Flat storage: index = tile.y * _data.width + tile.x");
        sb.AppendLine("        _grid = new UnityTileData[_data.width, _data.height];");
        sb.AppendLine("        foreach (var tile in _data.tiles)");
        sb.AppendLine("            _grid[tile.x, tile.y] = tile;");
        sb.AppendLine();
        sb.AppendLine("        // 3. Paint the Tilemap");
        sb.AppendLine("        //    Unity's Y axis points up, so negate Y to flip the map right-side up.");
        sb.AppendLine("        foreach (var tile in _data.tiles)");
        sb.AppendLine("        {");
        sb.AppendLine("            TileBase tb = ResolveTile(tile.tileType);");
        sb.AppendLine("            if (tb != null)");
        sb.AppendLine("                tilemap.SetTile(new Vector3Int(tile.x, -tile.y, 0), tb);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // 4. Visualise A* path (if present)");
        sb.AppendLine("        if (_data.lastPath?.waypoints is { Length: > 1 })");
        sb.AppendLine("        {");
        sb.AppendLine("            var wps = _data.lastPath.waypoints;");
        sb.AppendLine("            for (int i = 0; i < wps.Length - 1; i++)");
        sb.AppendLine("                Debug.DrawLine(");
        sb.AppendLine("                    new Vector3(wps[i].x + 0.5f,   -wps[i].y   - 0.5f, 0),");
        sb.AppendLine("                    new Vector3(wps[i+1].x + 0.5f, -wps[i+1].y - 0.5f, 0),");
        sb.AppendLine("                    Color.magenta, duration: 60f);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        Debug.Log($\"Loaded {_data.generatorType} map — \"");
        sb.AppendLine("                + $\"{_data.width}x{_data.height}, {_data.rooms.Length} rooms, seed {_data.seed}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // Map tileType string → TileBase asset");
        sb.AppendLine("    TileBase ResolveTile(string tileType) => tileType switch");
        sb.AppendLine("    {");
        sb.AppendLine("        \"Floor\"    => floorTile,");
        sb.AppendLine("        \"Wall\"     => wallTile,");
        sb.AppendLine("        \"Door\"     => doorTile,");
        sb.AppendLine("        \"Corridor\" => corridorTile,");
        sb.AppendLine("        _          => null");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    // Helper: world-space tile query");
        sb.AppendLine("    public bool TryGetTile(int x, int y, out UnityTileData tile)");
        sb.AppendLine("    {");
        sb.AppendLine("        tile = default;");
        sb.AppendLine("        if (x < 0 || x >= _data.width || y < 0 || y >= _data.height) return false;");
        sb.AppendLine("        tile = _grid[x, y];");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void TilemapTip(StringBuilder sb, string generatorType)
    {
        sb.AppendLine("## Tilemap Integration Tips");
        sb.AppendLine();
        sb.AppendLine("**Batch painting** — For large maps, replace the per-tile `SetTile` loop with a");
        sb.AppendLine("single `Tilemap.SetTilesBlock(BoundsInt, TileBase[])` call. Build a `TileBase[]`");
        sb.AppendLine("in the same row-major order and pass `new BoundsInt(0, -height+1, 0, width, height, 1)`");
        sb.AppendLine("as the bounds (accounting for the Y-flip).");
        sb.AppendLine();
        sb.AppendLine("**Colliders** — Add a `TilemapCollider2D` + `CompositeCollider2D` to the Wall");
        sb.AppendLine("layer and set the tilemap's Collision Type to `Sprite`. Non-walkable tiles");
        sb.AppendLine("(`isWalkable == false`) will automatically generate merged colliders.");
        sb.AppendLine();

        if (generatorType == "Terrain")
        {
            sb.AppendLine("**Biome layer** — This map includes `biomeType` per tile. Create a second");
            sb.AppendLine("`Tilemap` GameObject (child of the same Grid, higher sorting order) and");
            sb.AppendLine("populate it with biome-specific overlay tiles using the same loop,");
            sb.AppendLine("keying on `tile.biomeType` instead of `tile.tileType`:");
            sb.AppendLine();
            sb.AppendLine("```csharp");
            sb.AppendLine("var biomeTiles = new Dictionary<string, TileBase>");
            sb.AppendLine("{");
            sb.AppendLine("    [\"DeepWater\"]    = deepWaterTile,");
            sb.AppendLine("    [\"ShallowWater\"] = shallowWaterTile,");
            sb.AppendLine("    [\"Beach\"]        = beachTile,");
            sb.AppendLine("    [\"Grassland\"]    = grasslandTile,");
            sb.AppendLine("    [\"Forest\"]       = forestTile,");
            sb.AppendLine("    [\"Mountain\"]     = mountainTile,");
            sb.AppendLine("    [\"Snow\"]         = snowTile,");
            sb.AppendLine("};");
            sb.AppendLine("```");
            sb.AppendLine();
        }

        sb.AppendLine("**Rule Tiles** — Replace simple `TileBase` assets with Unity's `RuleTile`");
        sb.AppendLine("(from the 2D Extras package) to get automatic wall auto-tiling based on");
        sb.AppendLine("neighbour adjacency — no code changes required.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void Stats(StringBuilder sb, Map map, int seed, string generatorType)
    {
        sb.AppendLine("## Stats");
        sb.AppendLine();
        sb.AppendLine("| Field        | Value |");
        sb.AppendLine("|--------------|-------|");
        sb.AppendLine($"| Generator    | {generatorType} |");
        sb.AppendLine($"| Seed         | {seed} |");
        sb.AppendLine($"| Map size     | {map.Width}×{map.Height} |");
        sb.AppendLine($"| Rooms        | {map.Rooms.Count} |");
        sb.AppendLine($"| Total tiles  | {map.Width * map.Height} |");
        sb.AppendLine($"| Generated at | {DateTime.UtcNow:O} |");
    }
}
